/**
 * The kitchen words, translated by hand.
 *
 * Two reasons this exists rather than sending everything to the service.
 *
 * Quality: a translator given the single word "Oil" with no sentence around it
 * has no way to know this is a kitchen, and MyMemory duly returned "Ropa" —
 * crude oil, the kind that comes out of the ground. Short ingredient names are
 * exactly where machine translation is weakest, and exactly where being wrong
 * is most visible.
 *
 * Reach: a few hundred names cover 94% of every ingredient mention in the
 * library, because every second recipe wants onion, garlic and salt. That is
 * what makes a hand-written list practical here at all — the shopping list and
 * the ingredient panel are translated instantly, offline, with no request to
 * make and no daily allowance to run out. A name that isn't here stays as the
 * library wrote it, which on a shopping list is worth more than a guess.
 */

import { useLang } from "./i18n"

const PL: Record<string, string> = {
    // the constants of every recipe
    "salt": "sól",
    "pepper": "pieprz",
    "black pepper": "czarny pieprz",
    "white pepper": "biały pieprz",
    "cayenne pepper": "pieprz cayenne",
    "peppercorns": "ziarna pieprzu",
    "salt and pepper": "sól i pieprz",
    "water": "woda",
    "sugar": "cukier",
    "brown sugar": "cukier trzcinowy",
    "caster sugar": "cukier drobny",
    "icing sugar": "cukier puder",
    "honey": "miód",
    "flour": "mąka",
    "plain flour": "mąka pszenna",
    "all purpose flour": "mąka uniwersalna",
    "cornstarch": "skrobia kukurydziana",
    "corn flour": "mąka kukurydziana",
    "breadcrumbs": "bułka tarta",
    "baking powder": "proszek do pieczenia",
    "yeast": "drożdże",

    // fats and liquids
    "oil": "olej",
    "olive oil": "oliwa z oliwek",
    "extra virgin olive oil": "oliwa z oliwek extra virgin",
    "vegetable oil": "olej roślinny",
    "sunflower oil": "olej słonecznikowy",
    "sesame seed oil": "olej sezamowy",
    "sesame oil": "olej sezamowy",
    "coconut oil": "olej kokosowy",
    "butter": "masło",
    "unsalted butter": "masło niesolone",
    "vinegar": "ocet",
    "red wine vinegar": "ocet z czerwonego wina",
    "white wine vinegar": "ocet z białego wina",
    "rice vinegar": "ocet ryżowy",
    "balsamic vinegar": "ocet balsamiczny",
    "white wine": "białe wino",
    "red wine": "czerwone wino",

    // the vegetable drawer
    "garlic": "czosnek",
    "garlic clove": "ząbek czosnku",
    "garlic cloves": "ząbki czosnku",
    "onion": "cebula",
    "onions": "cebula",
    "red onions": "czerwona cebula",
    "red onion": "czerwona cebula",
    "spring onions": "dymka",
    "scallions": "dymka",
    "shallots": "szalotka",
    "leek": "por",
    "carrots": "marchew",
    "carrot": "marchew",
    "potatoes": "ziemniaki",
    "potato": "ziemniak",
    "sweet potato": "batat",
    "tomato": "pomidor",
    "tomatoes": "pomidory",
    "cherry tomatoes": "pomidorki koktajlowe",
    "tinned tomatoes": "pomidory z puszki",
    "chopped tomatoes": "pomidory krojone",
    "tomato puree": "koncentrat pomidorowy",
    "celery": "seler naciowy",
    "cucumber": "ogórek",
    "cabbage": "kapusta",
    "mushrooms": "pieczarki",
    "spinach": "szpinak",
    "lettuce": "sałata",
    "broccoli": "brokuł",
    "cauliflower": "kalafior",
    "aubergine": "bakłażan",
    "courgette": "cukinia",
    "courgettes": "cukinia",
    "peas": "groszek",
    "green beans": "fasolka szparagowa",
    "sweetcorn": "kukurydza",
    "red pepper": "papryka czerwona",
    "green pepper": "papryka zielona",
    "yellow pepper": "papryka żółta",
    "red chilli": "czerwone chilli",
    "green chilli": "zielone chilli",
    "chilli": "chilli",
    "ginger": "imbir",
    "beetroot": "burak",
    "pumpkin": "dynia",

    // meat and fish
    "chicken": "kurczak",
    "chicken breast": "pierś z kurczaka",
    "chicken breasts": "piersi z kurczaka",
    "chicken thighs": "udka z kurczaka",
    "beef": "wołowina",
    "ground beef": "mielona wołowina",
    "minced beef": "mielona wołowina",
    "pork": "wieprzowina",
    "lamb": "jagnięcina",
    "bacon": "boczek",
    "ham": "szynka",
    "sausages": "kiełbaski",
    "chorizo": "chorizo",
    "salmon": "łosoś",
    "tuna": "tuńczyk",
    "cod": "dorsz",
    "prawns": "krewetki",
    "anchovies": "anchois",

    // dairy
    "milk": "mleko",
    "cream": "śmietanka",
    "double cream": "śmietanka kremówka",
    "sour cream": "śmietana",
    "creme fraiche": "creme fraiche",
    "greek yogurt": "jogurt grecki",
    "yogurt": "jogurt",
    "cheese": "ser",
    "cheddar cheese": "ser cheddar",
    "parmesan": "parmezan",
    "mozzarella": "mozzarella",
    "feta": "feta",
    "egg": "jajko",
    "eggs": "jajka",
    "egg yolks": "żółtka",

    // the herb and spice shelf
    "parsley": "pietruszka",
    "coriander": "kolendra",
    "cilantro": "kolendra",
    "basil": "bazylia",
    "mint": "mięta",
    "dill": "koperek",
    "chives": "szczypiorek",
    "thyme": "tymianek",
    "rosemary": "rozmaryn",
    "oregano": "oregano",
    "sage": "szałwia",
    "bay leaf": "liść laurowy",
    "bay leaves": "liście laurowe",
    "paprika": "papryka mielona",
    "smoked paprika": "papryka wędzona",
    "cumin": "kmin rzymski",
    "ground cumin": "mielony kmin rzymski",
    "turmeric": "kurkuma",
    "cinnamon": "cynamon",
    "nutmeg": "gałka muszkatołowa",
    "allspice": "ziele angielskie",
    "cloves": "goździki",
    "cardamom": "kardamon",
    "saffron": "szafran",
    "star anise": "anyż gwiazdkowy",
    "vanilla": "wanilia",
    "curry powder": "curry w proszku",
    "chilli powder": "chilli w proszku",
    "garam masala": "garam masala",

    // cupboard
    "rice": "ryż",
    "basmati rice": "ryż basmati",
    "pasta": "makaron",
    "spaghetti": "spaghetti",
    "noodles": "makaron",
    "rice noodles": "makaron ryżowy",
    "bread": "chleb",
    "soy sauce": "sos sojowy",
    "fish sauce": "sos rybny",
    "oyster sauce": "sos ostrygowy",
    "worcestershire sauce": "sos worcestershire",
    "hot sauce": "ostry sos",
    "ketchup": "ketchup",
    "mayonnaise": "majonez",
    "mustard": "musztarda",
    "chicken stock": "bulion drobiowy",
    "beef stock": "bulion wołowy",
    "vegetable stock": "bulion warzywny",
    "coconut milk": "mleko kokosowe",
    "chickpeas": "ciecierzyca",
    "lentils": "soczewica",
    "kidney beans": "fasola czerwona",
    "chocolate": "czekolada",
    "cocoa": "kakao",
    "peanuts": "orzeszki ziemne",
    "almonds": "migdały",
    "walnuts": "orzechy włoskie",
    "cashews": "nerkowce",
    "raisins": "rodzynki",
    "sesame seeds": "sezam",

    // fruit
    "lemon": "cytryna",
    "lemon juice": "sok z cytryny",
    "lime": "limonka",
    "lime juice": "sok z limonki",
    "orange": "pomarańcza",
    "apple": "jabłko",
    "banana": "banan",
    "strawberries": "truskawki",
    "coconut": "kokos",
    "olives": "oliwki",

    // --- the long tail that still turns up often ---
    "scotch bonnet": "papryczka scotch bonnet",
    "tinned tomatos": "pomidory z puszki",
    "plum tomatoes": "pomidory śliwkowe",
    "sun-dried tomatoes": "suszone pomidory",
    "sundried tomatoes": "suszone pomidory",
    "tomato sauce": "sos pomidorowy",
    "tomato ketchup": "ketchup",
    "basil leaves": "listki bazylii",
    "coriander leaves": "listki kolendry",
    "dried oregano": "suszone oregano",
    "kosher salt": "sól gruboziarnista",
    "sea salt": "sól morska",
    "hotsauce": "ostry sos",
    "garlic powder": "czosnek granulowany",
    "onion powder": "cebula granulowana",
    "ground ginger": "imbir mielony",
    "ground coriander": "kolendra mielona",
    "cumin seeds": "nasiona kminu rzymskiego",
    "chilli flakes": "płatki chilli",
    "chili flakes": "płatki chilli",
    "red pepper flakes": "płatki chilli",
    "chili powder": "chilli w proszku",
    "cinnamon stick": "laska cynamonu",
    "harissa spice": "przyprawa harissa",
    "pita bread": "chleb pita",
    "baguette": "bagietka",
    "heavy cream": "śmietanka kremówka",
    "jasmine rice": "ryż jaśminowy",
    "macaroni": "makaron rurki",
    "bean sprouts": "kiełki fasoli",
    "thai red curry paste": "czerwona pasta curry",
    "red curry paste": "czerwona pasta curry",
    "thai green curry paste": "zielona pasta curry",
    "tamarind paste": "pasta tamaryndowa",
    "chicken stock cube": "kostka rosołowa",
    "black olives": "czarne oliwki",
    "green olives": "zielone oliwki",
    "dry sherry": "wytrawna sherry",
    "dry white wine": "wytrawne białe wino",
    "apple cider vinegar": "ocet jabłkowy",
    "sesame seed": "sezam",
    "pine nuts": "orzeszki piniowe",
    "white cabbage": "kapusta biała",
    "red cabbage": "kapusta czerwona",
    "kale": "jarmuż",
    "rocket": "rukola",
    "fennel": "koper włoski",
    "avocado": "awokado",
    "egg plants": "bakłażany",
    "challots": "szalotka",
    "lamb mince": "mielona jagnięcina",
    "lamb leg": "udziec jagnięcy",
    "chicken legs": "nogi z kurczaka",
    "ground pork": "mielona wieprzowina",
    "minced pork": "mielona wieprzowina",
    "sirloin steak": "polędwica wołowa",
    "beef brisket": "mostek wołowy",
    "raw king prawns": "surowe krewetki królewskie",
    "squid": "kalmary",
    "lard": "smalec",
    "parmesan cheese": "parmezan",
    "cannellini beans": "fasola cannellini",
    "black beans": "czarna fasola",
    "butter beans": "fasola biała",
    "dijon mustard": "musztarda dijon",
    "rapeseed oil": "olej rzepakowy",

    // --- the rest of what the library actually asks for ---
    "garlic granules": "czosnek granulowany",
    "garlic bulb": "główka czosnku",
    "minced garlic": "czosnek mielony",
    "chopped onion": "posiekana cebula",
    "onion salt": "sól cebulowa",
    "celery salt": "sól selerowa",
    "seasoning": "przyprawy",
    "all-purpose seasoning": "przyprawa uniwersalna",
    "starch": "skrobia",
    "self-raising flour": "mąka z proszkiem do pieczenia",
    "granulated sugar": "cukier kryształ",
    "golden caster sugar": "drobny cukier trzcinowy",
    "muscovado sugar": "cukier muscovado",
    "palm sugar": "cukier palmowy",
    "clear honey": "miód płynny",
    "molasses": "melasa",
    "shortening": "tłuszcz piekarski",
    "suet": "łój",
    "goose fat": "smalec gęsi",
    "ghee": "masło klarowane",

    // oils, vinegars, things poured in
    "peanut oil": "olej arachidowy",
    "ground nut oil": "olej arachidowy",
    "canola oil": "olej rzepakowy",
    "white vinegar": "ocet spirytusowy",
    "cider vinegar": "ocet jabłkowy",
    "sherry vinegar": "ocet sherry",
    "cooking wine": "wino do gotowania",
    "brandy": "brandy",
    "beer": "piwo",
    "orange juice": "sok pomarańczowy",
    "boiling water": "wrząca woda",

    // vegetables
    "swede": "brukiew",
    "turnips": "rzepa",
    "celeriac": "seler korzeniowy",
    "jerusalem artichokes": "topinambur",
    "asparagus": "szparagi",
    "broad beans": "bób",
    "sugar snap peas": "groszek cukrowy",
    "butternut squash": "dynia piżmowa",
    "squash": "dynia",
    "zucchini": "cukinia",
    "sweet potatoes": "bataty",
    "new potatoes": "młode ziemniaki",
    "baby new potatoes": "młode ziemniaki",
    "jersey royal potatoes": "młode ziemniaki",
    "small potatoes": "małe ziemniaki",
    "red potatoes": "ziemniaki czerwone",
    "floury potatoes": "ziemniaki mączyste",
    "russet potato": "ziemniak russet",
    "savoy cabbage": "kapusta włoska",
    "napa cabbage": "kapusta pekińska",
    "iceberg lettuce": "sałata lodowa",
    "pak choi": "pak choi",
    "chinese broccoli": "brokuł chiński",
    "daikon radish": "rzodkiew daikon",
    "bamboo shoot": "pędy bambusa",
    "water chestnut": "kasztan wodny",
    "shiitake mushrooms": "grzyby shiitake",
    "oyster mushrooms": "boczniaki",
    "chestnut mushroom": "pieczarka brązowa",
    "fennel bulb": "bulwa kopru włoskiego",
    "sauerkraut": "kiszona kapusta",
    "dill pickles": "ogórki kiszone",
    "capers": "kapary",
    "horseradish": "chrzan",
    "jalapeno": "jalapeño",
    "birds-eye chillies": "papryczki ptasie oko",
    "roasted pepper": "papryka pieczona",
    "romano pepper": "papryka romano",
    "stir-fry vegetables": "warzywa na patelnię",
    "diced tomatoes": "pomidory w kostce",
    "passata": "passata",
    "lemons": "cytryny",
    "lemon zest": "skórka cytrynowa",
    "orange zest": "skórka pomarańczowa",
    "dried apricots": "suszone morele",
    "prunes": "suszone śliwki",
    "pineapple chunks": "kawałki ananasa",

    // meat and fish
    "beef fillet": "polędwica wołowa",
    "flank steak": "stek z boku",
    "beef shin": "goleń wołowa",
    "oxtail": "ogon wołowy",
    "corned beef": "peklowana wołowina",
    "pork shoulder": "łopatka wieprzowa",
    "pork chops": "kotlety wieprzowe",
    "pork tenderloin": "polędwiczka wieprzowa",
    "pork belly slices": "plastry boczku",
    "pork back ribs": "żeberka wieprzowe",
    "lamb shoulder": "łopatka jagnięca",
    "lamb loin chops": "kotlety jagnięce",
    "lamb kidney": "nerki jagnięce",
    "goat meat": "mięso kozie",
    "chicken wings": "skrzydełka z kurczaka",
    "chicken drumsticks": "podudzia z kurczaka",
    "chicken liver": "wątróbka drobiowa",
    "shrimp": "krewetki",
    "king prawns": "krewetki królewskie",
    "tiger prawns": "krewetki tygrysie",
    "raw tiger prawns": "surowe krewetki tygrysie",
    "dried shrimp": "suszone krewetki",
    "mussels": "małże",
    "clams": "małże",
    "white fish": "biała ryba",
    "fish fillet": "filet rybny",
    "anchovy fillet": "filet anchois",
    "haddock": "łupacz",
    "smoked haddock": "wędzony łupacz",
    "salt cod": "solony dorsz",
    "codfish bulljaw": "solony dorsz",
    "frozen seafood mix": "mrożone owoce morza",

    // dairy
    "whole milk": "mleko pełnotłuste",
    "whipping cream": "śmietanka do ubijania",
    "coconut cream": "śmietanka kokosowa",
    "natural yoghurt": "jogurt naturalny",
    "goats cheese": "ser kozi",
    "swiss cheese": "ser szwajcarski",
    "gruyère": "ser gruyère",
    "gruyere": "ser gruyère",
    "pecorino": "ser pecorino",
    "mozzarella balls": "kulki mozzarelli",
    "shredded mexican cheese": "tarty ser meksykański",
    "egg white": "białko jaja",
    "egg wash": "roztrzepane jajko do smarowania",

    // herbs, spices, sauces
    "marjoram": "majeranek",
    "summer savoury": "cząber",
    "fresh thyme": "świeży tymianek",
    "dried mint": "suszona mięta",
    "dried dill": "suszony koperek",
    "chopped parsley": "posiekana pietruszka",
    "freshly chopped parsley": "świeżo posiekana pietruszka",
    "cilantro leaves": "listki kolendry",
    "coriander seeds": "nasiona kolendry",
    "fennel seeds": "nasiona kopru włoskiego",
    "caraway seed": "kminek",
    "ground turmeric": "kurkuma mielona",
    "turmeric powder": "kurkuma w proszku",
    "ground cinnamon": "cynamon mielony",
    "ground nutmeg": "gałka muszkatołowa mielona",
    "ground allspice": "ziele angielskie mielone",
    "ground clove": "goździki mielone",
    "ground black pepper": "czarny pieprz mielony",
    "sichuan pepper": "pieprz syczuański",
    "mustard powder": "musztarda w proszku",
    "english mustard": "musztarda angielska",
    "hot chilli powder": "ostra papryka chilli",
    "red chilli powder": "czerwona papryka chilli",
    "sweet smoked paprika": "słodka papryka wędzona",
    "chinese five spice powder": "chińska przyprawa pięciu smaków",
    "jamaican curry powder": "jamajskie curry",
    "lemongrass": "trawa cytrynowa",
    "lemongrass stalks": "łodygi trawy cytrynowej",
    "galangal": "galangal",
    "lime leaves": "liście limonki",
    "kaffir lime leaves": "liście limonki kaffir",
    "makrut lime leaves": "liście limonki kaffir",
    "ginger paste": "pasta imbirowa",
    "ginger garlic paste": "pasta imbirowo-czosnkowa",
    "red pepper paste": "pasta z czerwonej papryki",
    "sweet chilli sauce": "słodki sos chilli",
    "chilli sauce": "sos chilli",
    "garlic sauce": "sos czosnkowy",
    "barbeque sauce": "sos barbecue",
    "chimichurri sauce": "sos chimichurri",

    // cupboard
    "chicken broth": "bulion drobiowy",
    "fish stock": "bulion rybny",
    "lamb stock": "bulion jagnięcy",
    "vegetable stock cube": "kostka warzywna",
    "paella rice": "ryż do paelli",
    "brown rice": "ryż brązowy",
    "sushi rice": "ryż do sushi",
    "couscous": "kuskus",
    "quinoa": "komosa ryżowa",
    "lasagne sheets": "płaty lasagne",
    "vermicelli pasta": "makaron nitki",
    "vermicelli rice noodles": "ryżowy makaron nitki",
    "rice stick noodles": "wstążki ryżowe",
    "brown rice noodle": "makaron z brązowego ryżu",
    "brown lentils": "soczewica brązowa",
    "dried white beans": "suszona fasola biała",
    "soya bean": "soja",
    "tofu": "tofu",
    "peanut butter": "masło orzechowe",
    "roasted peanut": "prażone orzeszki ziemne",
    "cashew nuts": "orzechy nerkowca",
    "puff pastry": "ciasto francuskie",
    "shortcrust pastry": "kruche ciasto",
    "crusty bread": "chrupiące pieczywo",
    "rye bread": "chleb żytni",
    "naan bread": "chlebek naan",
    "corn tortillas": "tortille kukurydziane",
    "sesame seed burger buns": "bułki z sezamem",
    "rice paper sheets": "papier ryżowy",
    "mirin": "mirin",
    "sake": "sake",

    // last of the recurring ones; what is left after this is proper nouns
    // (jamón ibérico, pul biber) that a Polish kitchen calls by the same name
    "free-range egg, beaten": "jajko z wolnego wybiegu, roztrzepane",
    "italian fennel sausages": "włoskie kiełbaski z koprem",
    "duck legs": "udka z kaczki",
    "rice wine": "wino ryżowe",
    "ginger cordial": "syrop imbirowy",
    "pickle juice": "zalewa z ogórków",
    "cold water": "zimna woda",
    "udon noodles": "makaron udon",
    "linguine pasta": "makaron linguine",
    "fettuccine": "fettuccine",
    "bowtie pasta": "makaron kokardki",
    "filo pastry": "ciasto filo",
    "buns": "bułki",
    "frozen peas": "mrożony groszek",
    "corn on the cob": "kolba kukurydzy",
    "hispi (sweetheart) cabbage": "kapusta spiczasta",
    "hummus": "hummus",
    "tahini": "tahini",
    "enchilada sauce": "sos enchilada",
    "fajita seasoning": "przyprawa do fajitas",
    "shredded monterey jack cheese": "tarty ser monterey jack",
}

/**
 * The house translation for a kitchen word, if there is one.
 *
 * Matched on the trimmed, lowercased name, so "Olive Oil" and "olive oil" are
 * the same word. Anything not in here is somebody's own phrasing and goes to
 * the service.
 */
export function knownFood(name: string, lang: string): string | undefined {
    if (lang !== "pl") return undefined
    return PL[name.trim().toLowerCase()]
}


/**
 * Ingredient names in the current language.
 *
 * Answers from the list above and nowhere else — no request, no waiting, no
 * daily allowance to run out, and no chance of "Oil" coming back as crude oil.
 * A name that isn't on the list stays as the library wrote it, which is worth
 * more than a guess on a shopping list somebody is holding in a shop.
 */
export function useFoodWord(): (name: string) => string {
    const lang = useLang()
    return (name: string) => knownFood(name, lang) ?? name
}
